Update job templates

diff --git a/backend/faust/tests/fixtures/perlmutter_submission_script b/backend/faust/tests/fixtures/perlmutter_submission_script
--- a/backend/faust/tests/fixtures/perlmutter_submission_script
+++ b/backend/faust/tests/fixtures/perlmutter_submission_script
@@ -11,7 +11,6 @@
 #SBATCH --qos=science
 #SBATCH --constraint=gpu
 #SBATCH --nodes=8
-#SBATCH --ntasks-per-node=1
 #SBATCH --time=00:30:00
 #SBATCH --job-name=distiller-count-0
 #SBATCH --exclusive
@@ -34,7 +33,7 @@ list_files() {
   data_files=($(ssh changeme@$host ls $path/data_scan0*01_module*.data || error_exit "Error listing files: $host:$path."))
   number_of_files=${#data_files[@]}
   for ((i=0;i<$number_of_files;i++)); do
-    echo "changeme@$host:${data_files[$i]}" >> _ncem_files_0_$((i%24)).txt
+    echo "changeme@$host:${data_files[$i]}" >> _ncem_files_0_$((i%8)).txt
   done
 }
 
@@ -42,10 +41,15 @@ list_files localhost /mnt/nvmedata1
 list_files localhost /mnt/nvmedata4
 list_files localhost /mnt/nvmedata5
 
-srun -n 8 --cpus-per-task=2 --cpu-bind=cores bbcp.sh  || error_exit "Error bbcp srun command failed."
+srun -n 8 --cpus-per-task=2 --ntasks-per-node=1 --cpu-bind=cores bbcp.sh  || error_exit "Error bbcp srun command failed."
 
 rm _ncem_files_0_*.txt
 
-srun --exclusive -c 128 -n 8 shifter python3 /script --pad -l ${DW_JOB_STRIPED} -t 4.0 -s 1 --multi-pass || error_exit "Error shifter execution failed."
+# Remove any // ($DW_JOB_STRIPED has a trailing slash)
+BBCP_DEST_DIR=`echo "$PSCRATCH/ncem/0" |  sed 's/\/\//\//g'`
 
-cp ${DW_JOB_STRIPED}/data_scan*.h5  /tmp/data_scan1_id0_th4.0_electrons.h5 || error_exit "Failed to copy counted data to ncemhub."
+srun --exclusive -c 128 -n 8 shifter python3 /script --pad -l $BBCP_DEST_DIR -t 4.0 -s 1 --multi-pass || error_exit "Error shifter execution failed."
+
+cp ${BBCP_DEST_DIR}/data_scan*.h5  /tmp/data_scan1_id0_th4.0_electrons.h5 || error_exit "Failed to copy counted data to ncemhub."
+# Clean up
+rm -rf $PSCRATCH/ncem/0
